CanonicalLtd/maas-docs

src/navigation.tpl
Added these links under 'nodes', as suggested by Andres.
=> Added new storage files to navigation

src/en/installconfig-snippets.md, src/navigation.tpl
- Small edits for clarity
- Fixed formatting
- Added navigation
=> Converted dhcpsnippets to installconfig-snippets 

src/en/installconfig-lxd-install.md
New details come from changes to MAAS INSTALL.txt:
http://bazaar.launchpad.net/~maas-committers/maas/trunk/revision/5168#INSTALL.txt
=> Updated LXD install details

src/en/intro-concepts.md
Details taken from updated LP docs:
http://bazaar.launchpad.net/~maas-committers/maas/trunk/revision/5174
=> Added details on IP ranges to the subnet definition

src/en/intro-management.md, src/navigation.tpl
Fixed link and commented out Examples from nav.
=> Broken links

src/en/ref-release-notes.md, src/navigation.tpl
=> Added release notes

src/en/installconfig-install.md, src/en/installconfig-package-install.md, src/en/intro-about-maas.md, src/navigation.tpl
Fixed link but found a lot of other stuff that needed attention.
Fixes #88
=> Broken link

src/en/installconfig-images.md
=> added a missing conjunction

src/en/installconfig-proxy.md, src/en/manage-cli-common.md
Sorry Graham, more good stuff here.
=> more proxying changes

README.md
- updated to reflect new documentation structure
- refactored URLs that aren't part of the text (as these will need to be changed alongside the text itself)
=> updated readme to reflect recent changes in the documentation structure.

context.yaml
We will soon have a [TOC](https://github.com/CanonicalLtd/documentation-builder/issues/19) feature to assist with the long pages. :beers:
=> refactored menu; networking + user account

en/intro-concepts.md
This will need to be followed by a PR for 'node statuses' i guess.
=> Node actions

en/intro-concepts.md
Second attempt. Other PR closed.
=> Node statuses

en/intro-concepts.md, en/troubleshoot-faq.md
=> 2.1 new rescue mode

en/intro-concepts.md
=> broken includes off

en/installconfig-network-dev-discovery.md, en/metadata.yaml
=> 2.1 new device discovery

en/intro-management.md, en/manage-cli.md, en/metadata.yaml
=> issue #195 - API and dev links

en/index.md
=> issue 196 extraneous debian preseed

en/installconfig-add-nodes.md, en/installconfig-checklist.md, en/installconfig-hwe-kernels.md, en/installconfig-subnets-dhcp.md, en/installconfig-tags.md, en/manage-account.md, en/manage-cli-advanced.md, en/manage-cli-common.md, en/manage-cli-dhcp-snippets.md, en/manage-cli-images.md, en/manage-cli.md, en/manage-repos.md, en/manage-zones.md, en/troubleshoot-faq.md
Graham, check it over. If all good I can do the backporting.
=> added TOC to the files that need them

en/installconfig-networking.md, en/intro-concepts.md
=> added spaces-as-L2 feature

en/metadata.yaml
Add a link to the navigation to link to MAAS 1.9 documentation.
=> Update the master branch with a link to legacy docs

en/manage-backup.md, en/metadata.yaml
fixes  #97 
A new doc for backing up and restoring a MAAS 2.1 environment.
It would be good if @evilnick and @pmatulis could take a look over this in the first instance.
I've not added the doc to navigation yet, pending review or any discussions on this document.
=> MAAS backup and restore

en/installconfig-network-dhcp.md
=> backport dhcp from master to 2.1; after modifications

en/installconfig-images-import.md, en/installconfig-images.md
=> abstract links; fixed issue 279; minor rewording

en/installconfig-network-ntp.md, en/installconfig-webui-conf-journey.md, en/manage-repos.md
=> abstract links for images

en/installconfig-network-proxy.md, en/installconfig-network-stp.md, en/installconfig-package-install.md, en/installconfig-power-types.md, en/installconfig-storage-erasure.md, en/installconfig-upgrade-to-2.md, en/intro-architecture.md, en/manage-cli-common.md, en/manage-ha-postgresql.md, en/manage-zones.md
abstract links; rewording to upgrade page; minor rewording to others
=> links and images

en/release-notes-all.md, en/troubleshoot-faq.md, en/troubleshoot-getting-help.md
=> abstract links; refactored headers in release-notes-all.md

en/installconfig-network-dhcp.md, en/installconfig-network-subnet-management.md, en/intel-rsd.md
=> abstract links

en/release-notes-all.md, en/release-notes.md
Fixes #331 
Backport these two files to devel immediately and then backport historical notes to 2.1 and 2.0
=> [2.2b3] devel and historical release notes

en/manage-libmaas.md, en/metadata.yaml
=> new feature: API client (python-libmaas)

en/intel-rsd.md
Fixes #333 
Removed gobbledygook. Next, the same file will be updated to reflect web UI functionality.
=> intel RSD - reworded using info from beta3 release notes

en/intel-rsd.md, en/intro-concepts.md
=> added more intel RSD stuff; mostly web UI

en/contributing.md, en/index.md, en/installconfig-add-nodes.md, en/installconfig-block.md, en/installconfig-checklist.md, en/installconfig-commission-nodes.md, en/installconfig-images-import.md, en/installconfig-images-mirror.md, en/installconfig-iso-install.md, en/installconfig-network-dhcp.md, en/installconfig-network-ipv6.md, en/installconfig-networking.md, en/installconfig-nodes-deploy.md, en/installconfig-nodes-hw-testing.md, en/installconfig-nodes-ubuntu-kernels.md, en/installconfig-partitions.md, en/installconfig-rack.md, en/installconfig-storage.md, en/installconfig-tags.md, en/installconfig-webui.md, en/manage-account.md, en/manage-backup.md, en/manage-cli-advanced.md, en/manage-cli-common.md, en/manage-cli-dhcp-snippets.md, en/manage-cli-images.md, en/manage-cli.md, en/manage-ha.md, en/release-notes-all.md
This work reformats the admonitions so that they work with the standard extension.
Fixes #352
=> Reformat admonitions for standard extension

en/manage-cli-advanced.md
A changed admonition got included from PR #353
=> backport pr 351 to devel

.gitignore, en/manage-cli-advanced.md
An admonishment slipped in from PR #353 .
=> backport pr 351 to 2.1

en/api.md
Fixes #348 
This only exposes 4 headings. :crying_cat_face:
=> added TOC to api.md fwiw

.travis.yml
=> Add travis checks for doc-builder compatibility

en/release-notes-all.md, en/release-notes.md
Reformatted beta3 notes a little.
=> beta4 release notes

en/installconfig-iso-install.md, en/installconfig-package-install.md, en/installconfig-rack.md
=> update how to add a rackd

en/manage-cli.md
=> added maas-cli section

en/installconfig-commission-nodes.md, en/installconfig-nodes-deploy.md, en/intro-concepts.md, en/manage-cli-common.md
=> CLI allocate and deploy

en/installconfig-nodes-deploy.md, en/intro-concepts.md
=> more deploy stuff

en/intro-concepts.md
=> clarify reserved ip ranges

en/intel-rsd.md
=> RSD validation version blurb

en/installconfig-install.md, en/installconfig-package-install.md, en/installconfig-snap-install.md, en/metadata.yaml
=> add a snap install method

en/installconfig-images.md, en/intro-concepts.md, en/manage-cli-images.md
=> clarifying terminology for boot sources/resources

en/installconfig-nodes-kernel-boot-options.md, en/installconfig-nodes-ubuntu-kernels.md, en/manage-cli-advanced.md, en/manage-cli-kernels.md, en/metadata.yaml
=> Backport #471 to 2.2

en/nodes-comp-hw.md
=> Backport #478 to 2.2

en/intro-management.md, en/manage-cli.md, en/manage-zones.md, en/nodes-commission.md, en/nodes-power-types.md
=> Backport #484 to 2.2

en/manage-cli-advanced.md, en/manage-cli-common.md, en/manage-cli-dhcp-snippets.md, en/manage-cli-kernels.md, en/manage-cli-tags.md, en/manage-cli.md
=> Backport #489 to 2.2

en/contributing-git.md, en/installconfig-images.md, en/manage-libmaas.md
=> Backport #506 to 2.2

en/manage-cli-advanced.md, en/nodes-commission.md
=> change IP assignment mode

en/manage-cli-advanced.md, en/nodes-commission.md
=> Backport #505 to 2.2

en/manage-ha.md
=> Backport #509 to 2.2

en/nodes-kernel-options.md, en/nodes-kernels.md
=> Backport #512 to devel

en/nodes-kernel-options.md, en/nodes-kernels.md
=> Backport #512 to 2.2

en/metadata.yaml
=> Backport #522 to 2.2

en/metadata.yaml
=> Backport #522 to 2.1

en/metadata.yaml
=> Backport #522 to 2.0

en/release-notes.md
=> release notes for 2.3.0 alpha1/alpha2

en/release-notes.md
release notes for 2.3.0 alpha1/alpha2
=> bp-to-devel: Merge pull request #529 from degville/2.3-alpha-notes

en/installconfig-images.md
=> Backport #528 to 2.2

en/installconfig-images.md
=> Backport #528 to devel

en/installconfig-images.md
=> Backport #528 to 2.1

en/metadata.yaml
Remove top level link to 1.9 docs
=> bp-to-devel #522 1.9-remove-link

en/installconfig-upgrade-to-2.md
=> Added background details on IP ranges to the 1.9 migration doc

en/installconfig-upgrade-to-2.md
=> Backport #537 to devel

en/installconfig-upgrade-to-2.md
=> Backport #537 to 2.2

en/installconfig-upgrade-to-2.md
=> Backport #537 to 2.1

en/installconfig-upgrade-to-2.md
=> Backport #537 to 2.0

en/installconfig-upgrade-to-2.md, en/manage-ha-postgresql.md, en/metadata.yaml
=> 1.9  to 2.x migration

en/nodes-hw-scripts-cli.md
=> Hardware Testing scripts documentation - CLI

en/nodes-hw-testing.md
3 of 3 PRs to fix #536.
I will create another PR to link this into the menu metadata if/when these 3 are merged.
=> Hardware Testing scripts documentation - General

en/nodes-hw-testing.md
=> Backport #546 to devel

en/nodes-hw-testing.md
=> Backport #546 to 2.2

en/metadata.yaml
=> Backport #550 to devel

en/metadata.yaml
=> Backport #550 to 2.2

en/manage-account.md
=> Add details on pasting local id_rsa.pub

en/manage-account.md
=> Backport #562 to devel

en/manage-account.md
=> Backport #562 to 2.2

en/manage-ha.md
=> Backport #568 to 2.2

en/manage-ha.md
=> Backport #568 to 2.1

en/manage-ha.md
=> Backport #568 to 2.0

en/release-notes.md
=> release notes for 2.3.0 alpha3

en/release-notes.md
=> Backport #566 to devel

en/nodes-hw-scripts-cli.md
=> Backport #545 to devel

en/nodes-hw-scripts-cli.md
=> Backport #545 to 2.2

en/nodes-hw-scripts.md
=> Backport #577 to devel

en/nodes-hw-scripts.md
=> Backport #577 to 2.2

en/intro-concepts.md
=> Updated fabric definition

en/intro-concepts.md
=> Backport #582 to devel

en/intro-concepts.md
=> Backport #582 to 2.2

en/intro-concepts.md
=> bp #582 from degville/573-fabric to 2.1

en/manage-backup.md
=> Updated restore procedure to include permissions arguments

en/manage-backup.md
=> Backport #583 to devel

en/manage-backup.md
=> Backport #583 to 2.2

en/manage-backup.md
=> Backport #583 to 2.1

en/metadata.yaml, en/nodes-custom.md
=> Backport #592 to devel

en/metadata.yaml, en/nodes-custom.md
=> Backport #592 to 2.2

en/metadata.yaml, en/nodes-custom.md
=> Backport #592 to 2.1

en/metadata.yaml, en/nodes-custom.md
=> Backport #592 to 2.0

en/release-notes.md
=> Release nodes for 2.3.0beta1

en/release-notes.md
(I pressed the wrong button earlier!)
=> update after GH feedback.

en/release-notes.md
=> [cdu] Backport #600 to devel

en/release-notes.md
=> [cdu] Backport #601 to devel

en/nodes-custom.md
=> [cdu] Backport #605 to devel

en/nodes-custom.md
=> [cdu] Backport #605 to 2.2

en/nodes-custom.md
=> [cdu] Backport #605 to 2.1

en/nodes-custom.md
=> [cdu] Backport #605 to 2.0

en/installconfig-misc.md, en/metadata.yaml, en/nodes-custom.md
fixes #598
- ported custom node/preseed doc to 1.9
- updated links
- removed unused links
=> Port custom node/preseed doc to 1.9

en/release-notes.md
=> update release notes for 2.3.0b2

en/release-notes.md
=> [cdu] Backport #627 to devel

en/api-authentication.md, en/metadata.yaml
=> Migrated api-authentication to 2.x docs

en/api-authentication.md, en/metadata.yaml
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/637
=> Backport #637 to devel

en/api-authentication.md, en/metadata.yaml
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/637
=> Backport #637 to 2.2

en/api-authentication.md, en/metadata.yaml
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/637
=> Backport #637 to 2.1

en/api-authentication.md, en/metadata.yaml
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/637
=> Backport #637 to 2.0

en/manage-ha.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/644
=> Backport #644 to devel

en/manage-ha.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/644
=> Backport #644 to 2.2

en/manage-backup.md
=> Backup: extra details checking for running psql sessions.

en/intro-concepts.md, en/nodes-add.md, en/nodes-commission.md, en/nodes-deploy.md
=> Remove iSCSI references

en/manage-backup.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/642
=> Backport #642 to devel

en/manage-backup.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/642
=> Backport #642 to 2.2

en/manage-backup.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/642
=> Backport #642 to 2.1

en/manage-backup.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/642
=> Backport #642 to 2.0

en/intro-concepts.md, en/nodes-add.md, en/nodes-commission.md, en/nodes-deploy.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/648
=> Backport #648 to devel

en/nodes-hw-testing.md
=> Fixed broken link

en/nodes-hw-testing.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/656
=> Backport #656 to devel

en/nodes-hw-testing.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/656
=> Backport #656 to 2.2

en/metadata.yaml, en/nodes-hw-scripts-cli.md, en/nodes-hw-scripts-fields.md, en/nodes-hw-scripts.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/660
=> Backport #660 to devel

en/release-notes.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/659
=> Backport #659 to devel

en/metadata.yaml, en/nodes-hw-scripts-cli.md, en/nodes-hw-scripts-fields.md, en/nodes-hw-scripts.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/660
=> Backport #660 to 2.2

en/manage-cli-advanced.md
=> Reworded note for clarity

en/manage-cli-advanced.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/665
=> Backport #665 to devel

en/manage-cli-advanced.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/665
=> Backport #665 to 2.2

en/manage-cli-advanced.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/665
=> Backport #665 to 2.1

en/installconfig-network-dev-discovery.md, en/installconfig-network-dhcp.md, en/installconfig-network-subnet-management.md, en/installconfig-networking.md, en/installconfig-rack.md, en/installconfig-webui-conf-journey.md, en/metadata.yaml
- updated text for UI changes in the MAAS 2.3 release
- updated links for new images
- does not include updated text for the new node overview
images are in #669
=> 2.3 image updates - supporting text

en/installconfig-network-dev-discovery.md, en/installconfig-network-dhcp.md, en/installconfig-network-subnet-management.md, en/installconfig-networking.md, en/installconfig-rack.md, en/installconfig-webui-conf-journey.md, en/metadata.yaml
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/670
=> Backport #670 to devel

en/nodes-commission.md, en/nodes-hw-testing.md, en/nodes-kernels.md, en/nodes-power-types.md, en/nodes-tags.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/673
=> Backport #673 to devel

en/manage-ha.md
=> added small detail on DNS HA.

en/manage-ha.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/677
=> Backport #677 to devel

en/manage-ha.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/677
=> Backport #677 to 2.3

en/release-notes.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/680
=> Backport #680 to devel

en/release-notes.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/680
=> Backport #680 to 2.3

en/nodes-hw-scripts-fields.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/686
=> Backport #686 to devel

en/nodes-hw-scripts-fields.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/686
=> Backport #686 to 2.3

en/release-notes.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/693
=> Backport #693 to devel

en/release-notes.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/693
=> Backport #693 to 2.3

en/release-notes.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/696
=> Backport #696 to devel

en/release-notes.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/696
=> Backport #696 to 2.3

en/intro-concepts.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/699
=> Backport #699 to devel

en/intro-concepts.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/699
=> Backport #699 to 2.3

en/intro-concepts.md
Various updates to intro-concepts
=> Backport #699 to 2.0 (manual) from degville/556-intro-updates

en/installconfig-lxd-install.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/706
=> Backport #706 to devel

en/installconfig-lxd-install.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/706
=> Backport #706 to 2.3

en/installconfig-lxd-install.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/706
=> Backport #706 to 2.2

en/installconfig-lxd-install.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/706
=> Backport #706 to 2.1

en/manage-cli-advanced.md
Added procedure on how to add alias records (CNAME) and Mail eXchange (MX) records to DNS managed by MAAS.
=> Added advanced DNS record management

en/release-notes-all.md
fixes #713 
- added 2.3 to global release notes
- added contact us
=> Updates release notes to include 2.3

en/release-notes-all.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/715
=> Backport #715 to devel

en/release-notes-all.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/715
=> Backport #715 to 2.3

en/release-notes-all.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/715
=> Backport #715 to 2.2

en/release-notes-all.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/715
=> Backport #715 to 2.1

en/manage-cli-advanced.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/714
=> Backport #714 to devel

en/manage-cli-advanced.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/714
=> Backport #714 to 2.3

en/contributing-git.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/724
=> Backport #724 to 2.3

en/contributing-git.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/724
=> Backport #724 to 2.1

en/manage-cli-advanced.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/714
=> Backport #714 to 2.2

en/manage-cli-advanced.md
Added advanced DNS record management
=> Backport #713 to 2.1 (manual)

en/contributing-build.md, en/contributing-git.md, en/contributing-writing.md, en/metadata.yaml
=> backport contributing files to 2.0

en/metadata.yaml
=> fixed broken release notes link.

en/installconfig-install.md, en/installconfig-upgrade-postgres.md, en/metadata.yaml
@roaksoax I've updated your doc slightly and integrated it in to the devel docs. 
fixes #771
=> Updated installconfig-upgrade-postgres.md

en/manage-audit-events.md, en/metadata.yaml
- added renamed audit-event-logs from devel
- updated words for consistency with the wider documentation
- added to table of contents
fixes #769
=>  Audit Event Logs update

en/manage-audit-events.md, en/metadata.yaml
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/772
=> Backport #772 to devel

.travis.yml, en/metadata.yaml, en/nodes-hw-testing.md, en/nodes-scripts-cli.md, en/nodes-scripts.md, en/release-notes.md
Update to Commissioning and Hardware Testing Scripts
=> Manual backport #777 to devel

.travis.yml
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/778
=> Backport #778 to 2.3

.travis.yml
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/778
=> Backport #778 to 2.2

en/metadata.yaml, en/nodes-hw-testing.md, en/nodes-scripts-cli.md, en/nodes-scripts.md, en/release-notes.md
Update to Commissioning and Hardware Testing Scripts
=> Manual backport #777 to 2.3

en/metadata.yaml, en/nodes-hw-testing.md, en/nodes-scripts-cli.md, en/nodes-scripts.md, en/release-notes.md
Update to Commissioning and Hardware Testing Scripts
=> Manual backport #777 to 2.2

en/nodes-tags.md
=> quick fixed image link

en/metadata.yaml
fixes #750 
This completes the re-organisation around the new table of contents.
=> Add webui document to the toc.

en/nodes-tags.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/787
=> Backport #787 to devel

en/nodes-tags.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/787
=> Backport #787 to 2.3

en/nodes-tags.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/787
=> Backport #787 to 2.2

en/metadata.yaml
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/780
=> Backport #780 to devel

en/contact-us.md, en/metadata.yaml
=> New contact-us page

en/contact-us.md, en/metadata.yaml
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/793
=> Backport #793 to devel

en/manage-cli-advanced.md
fixes #800 
(also tested command to make sure they still work)
=> Replaced single quotes with double quotes to fix jq syntax.

en/manage-cli-advanced.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/801
=> Backport #801 to devel

en/api-authentication.md
=> Backport #806 to devel

en/api-authentication.md
=> Backport #806 to 2.3

en/api-authentication.md
=> Backport #806 to 2.2

en/api-authentication.md
=> Backport #806 to 2.1

en/api-authentication.md
=> Backport #806 to 2.0

en/api-authentication.md
=> Backport #806 to 1.9

app.py
QA
--
`./run` and check the site works properly
=> Remove redundant application_root

en/nodes-scripts.md
=> Removed duplicate metadata fields.

en/nodes-scripts.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/822
=> Backport #822 to devel

en/release-notes.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/825
=> Backport #825 to devel

en/metadata.yaml, en/nodes-scripts-cli.md
=> fix broken link to nodes-scripts-cli

en/api.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/835
=> Backport #835 to devel

en/installconfig-upgrade-to-2.md, en/manage-ha.md
=> Removed references to deprecated maas-dns package

en/release-notes.md
=> 2.4b2 release notes.

en/installconfig-upgrade-to-2.md, en/manage-ha.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/860
=> Backport #860 to devel

en/release-notes.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/863
=> Backport #863 to devel

en/comp-hw-virsh-pods.md, en/manage-cli-comp-hw.md, en/metadata.yaml
This PR adds a new page that details some of the extra capabilities that Virsh pods have that other pod types do not.  This PR also adds some content about how pods now have tags and a zone.
=> Add virsh pod content and pod updates.

en/metadata.yaml
fixes #848 
I had thought of putting this as the very top, but it's a relatively technical doc to be so prominently placed (imo), so I've settled in putting it in the user guide section. It will be linked to from the release notes and from the What's New doc (yet to be written).
=> Upgrade doc more visible in the toc.

en/installconfig-network-ntp.md, en/installconfig-network-proxy.md, en/installconfig-storage-erasure.md, en/installconfig-storage.md, en/intro-concepts.md, en/manage-account.md, en/nodes-commission.md, en/nodes-kernels.md, en/nodes-scripts.md
=> 2.4: Updated references to settings locations

en/installconfig-network-ntp.md, en/installconfig-network-proxy.md, en/installconfig-storage-erasure.md, en/installconfig-storage.md, en/intro-concepts.md, en/manage-account.md, en/nodes-commission.md, en/nodes-kernels.md, en/nodes-scripts.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/883
=> Backport #883 to 2.4

en/installconfig-checklist.md, en/installconfig-network-dhcp.md, en/installconfig-rack.md, en/installconfig-webui.md, en/manage-cli-advanced.md, en/manage-zones.md, en/metadata.yaml, en/nodes-add.md, en/nodes-commission.md, en/nodes-hw-testing.md, en/nodes-kernels.md, en/nodes-overview.md, en/nodes-power-types.md, en/nodes-tags.md
Zones renamed to AZs (Availability Zones). Machines, Devices and Controllers have been moved from Hardware to the top-level menu.
=> Top menu navigation updates to documentation

en/installconfig-checklist.md, en/installconfig-network-dhcp.md, en/installconfig-rack.md, en/installconfig-webui.md, en/manage-cli-advanced.md, en/manage-zones.md, en/metadata.yaml, en/nodes-add.md, en/nodes-commission.md, en/nodes-hw-testing.md, en/nodes-kernels.md, en/nodes-overview.md, en/nodes-power-types.md, en/nodes-tags.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/886
=> Backport #886 to devel

en/installconfig-checklist.md, en/installconfig-network-dhcp.md, en/installconfig-rack.md, en/installconfig-webui.md, en/manage-cli-advanced.md, en/manage-zones.md, en/metadata.yaml, en/nodes-add.md, en/nodes-commission.md, en/nodes-hw-testing.md, en/nodes-kernels.md, en/nodes-overview.md, en/nodes-power-types.md, en/nodes-tags.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/886
=> Backport #886 to 2.4

en/manage-cli-comp-hw.md, en/nodes-comp-hw.md
=> Manual backport #890 from degville/889-virsh to 2.4

en/api.md, en/release-notes.md
=> Updated release notes for 2.4b3

en/api.md, en/release-notes.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/894
=> Backport #894 to devel

en/api.md, en/release-notes.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/894
=> Backport #894 to 2.4

en/installconfig-network-ssl.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/906
=> Backport #906 to 2.4

en/release-notes.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/911
=> Backport #911 to devel

en/release-notes.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/911
=> Backport #911 to 2.4

en/nodes-custom.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/920
=> Backport #920 to devel

en/nodes-custom.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/920
=> Backport #920 to 2.4

en/nodes-custom.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/920
=> Backport #920 to 2.3

en/release-notes.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/929
=> Backport #929 to 2.4

en/release-notes.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/929
=> Backport #929 to devel

en/api.md
=> Updated API for 2.4.0

en/api.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/935
=> Backport #935 to devel

en/api.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/935
=> Backport #935 to 2.4

en/index.md, en/installconfig-block.md, en/installconfig-checklist.md, en/installconfig-commission-nodes.md, en/installconfig-images-import.md, en/installconfig-images-mirror.md, en/installconfig-network-dhcp.md, en/installconfig-network-ipv6.md, en/installconfig-networking.md, en/installconfig-nodes-deploy.md, en/installconfig-nodes-ubuntu-kernels.md, en/installconfig-partitions.md, en/installconfig-storage.md, en/installconfig-tags.md, en/installconfig-webui.md, en/manage-account.md, en/manage-backup.md, en/manage-cli-advanced.md, en/manage-cli-common.md, en/manage-cli-images.md
=> Fix admonitions in 2.0 docs

en/api.md
=> Remove misleading untagged VLAN reference

en/index.md, en/installconfig-storage.md, en/nodes-scripts-cli.md
=> Replace broken warning admonition with Negative

en/index.md, en/installconfig-storage.md, en/nodes-scripts-cli.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/944
=> Backport #944 to devel

en/index.md, en/installconfig-storage.md, en/nodes-scripts-cli.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/944
=> Backport #944 to 2.4

en/api.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/943
=> Backport #943 to devel

en/api.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/943
=> Backport #943 to 2.4

en/index.md, en/installconfig-images.md, en/intro-explore.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/952
=> Backport #952 to devel

en/index.md, en/installconfig-images.md, en/intro-explore.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/952
=> Backport #952 to 2.4

en/index.md, en/installconfig-images.md, en/intro-explore.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/952
=> Backport #952 to 2.3

en/index.md
=> Fixed number of installation methods (2.3)

en/installconfig-lxd-install.md
=> fixed/tested reported issue with LXD and outdated app armor key

en/installconfig-lxd-install.md
=> Backport #960 to devel

en/installconfig-lxd-install.md
=> Backport #960 to 2.4

en/installconfig-lxd-install.md
=> Backport #960 to 2.3

en/installconfig-lxd-install.md
=> Backport #960 to 2.2

en/installconfig-lxd-install.md
=> Backport #960 to 2.1

en/installconfig-lxd-install.md
=> Backport #960 to 2.0

en/nodes-commission.md, en/nodes-tags.md
=>  fixed broken 2.2/2.3 references to missing images

en/nodes-commission.md
=> fixed links to old images

en/installconfig-upgrade-to-2.md, en/intro-explore.md, en/manage-backup.md, en/metadata.yaml
=> updated references to 18.04 where relevant

en/installconfig-upgrade-to-2.md, en/intro-explore.md, en/manage-backup.md, en/metadata.yaml
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/974
=> Backport #974 to devel

en/installconfig-upgrade-to-2.md, en/intro-explore.md, en/manage-backup.md, en/metadata.yaml
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/974
=> Backport #974 to 2.4

package.json
Point search at www.ubuntu.com until we have custom search working on this project.
- Run `./run build`
- Open a doc HTML page from the build directory
- Search and check it searches on www.ubuntu.com
=> Point search at www.ubuntu.com

en/installconfig-snap-install.md
https://bugs.launchpad.net/maas/+bug/1767766
=> Added node about devmode in install in response to bug

en/manage-cli-comp-hw.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1047
=> Backport #1047 to 2.5

en/intro-concepts.md, en/manage-cli-comp-hw.md, en/manage-kvm-pods-networking.md, en/manage-pods-webui.md, en/metadata.yaml, en/nodes-comp-hw.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1055
=> Backport #1055 to 2.5

en/intro-new.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1057
=> Backport #1057 to 2.5

en/manage-maas-security.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1059
=> Backport #1059 to 2.5

en/nodes-add.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1065
=> Backport #1065 to 2.5

en/manage-search.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1071
=> Backport #1071 to 2.5

en/installconfig-lxd-install.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1079
=> Backport #1079 to 2.5

en/nodes-custom.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1086
=> Backport #1086 to devel

en/nodes-custom.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1086
=> Backport #1086 to 2.5

en/nodes-custom.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1086
=> Backport #1086 to 2.4

en/nodes-custom.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1086
=> Backport #1086 to 2.3

en/nodes-scripts.md
The parameter and result sections have been expanded to include more detailed documentation. Simple examples have also been added to make the documentation more clear. I have also removed references to the 'timeout' parameter as this is not currently accessible by the user.
=> Add parameter and result examples

en/api.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1117
=> Backport #1117 to 2.5

en/api.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1120
=> Backport #1120 to 2.5

en/nodes-overview.md, en/nodes-tags.md
Fixed some broken 2.6 image paths
- Test the new paths work on staging: https://docs.staging.maas.io/devel/en/nodes-overview
=> Fix from 2.6 image paths

en/intro-new.md, en/metadata.yaml, redirects.map
=> Sync master

en/intro-communication.md
Just fixing a typo in a section title...
=> Fix typo in section title

convert_api.sh, en/api.md
Simplify convert_api.sh to match current structure and update API docs for 2.9.1
=> Convert api docs 2.9
