CanonicalLtd/maas-docs

- src/en/intro-about-maas.md
- src/navigation.tpl
Expand the About MAAS page as this is going to be the default landing page/index.html for the MAAS docs.
- Prominent links to the installation instructions
- Merged the majority of the Fundamentals section, moving the simple setup example to the bottom as this seemed a more logical place in its new position
- Commented out the link to the fundamentals doc from the navigation
> Expanded About MAAS to better serve as landing page

- src/en/installconfig-package-install.md
This ncurses dialog is for adding a rack/cluster controller in 1.9. It certainly is not for seen when installing MAAS via the 'maas' metapackage. For completeness, when a rack controller *is* added in 2.0 the dialog is not ncurses-based.
> remove rack controller ncurses dialog

- src/en/configure.md
- src/en/installing-ubuntu.md
- Point to media using the same `./media` standard used throughout the rest of the documentation
- Add alt tags to images
> Make links to media consistent

- context.yaml
So that these variables can be used in a generic template, to satisfy: https://github.com/ubuntudesign/docs.ubuntu.com/issues/3
> Add `site_title` and `logo_url` to context

- en/metadata.yaml
Add a link to the navigation to link to MAAS 1.9 documentation.
> Update the 2.1 branch with a link to legacy docs

- en/api.md
- en/metadata.yaml
This is my best attempt at converting the API page to markdown.
This was generated with:
``` bash
cat ../api.rst | sed -n '/========/,$p' | pandoc --from=rst --to=markdown+backtick_code_blocks+pipe_tables+definition_lists+compact_definition_lists --column=78 --atx-headers | sed 's/^:   /\n/' | sed 's/    - /- /' | sed -E 's/^`(.+)`$/##### `\1`/' | sed -E 's/    ((param|type) .*|return|rtype)/- `\1`/' | sed -E 's/    ://' | sed 's/^    //' > en/api.md
```
After generating the ReST file from the MAAS codebase.
Check you think it looks acceptable.
> Add the API page for 2.1

- en/api.md
- en/metadata.yaml
This is my best attempt at converting the API page to markdown.
This was generated with:
``` bash
cat ../api.rst | sed -n '/========/,$p' | pandoc --from=rst --to=markdown+backtick_code_blocks+pipe_tables+definition_lists+compact_definition_lists --column=78 --atx-headers | sed 's/^:   /\n/' | sed 's/    - /- /' | sed -E 's/^`(.+)`$/##### `\1`/' | sed -E 's/    ((param|type) .*|return|rtype)/- `\1`/' | sed -E 's/    ://' | sed 's/^    //' > en/api.md
```
After generating the ReST file from the MAAS codebase.
Check you think it looks acceptable.
> Add the API page for 2.0

- en/api.md
- en/metadata.yaml
This is my best attempt at converting the API page to markdown.
This was generated with:
``` bash
cat ../api.rst | sed -n '/========/,$p' | pandoc --from=rst --to=markdown+backtick_code_blocks+pipe_tables+definition_lists+compact_definition_lists --column=78 --atx-headers | sed 's/^:   /\n/' | sed 's/    - /- /' | sed -E 's/^`(.+)`$/##### `\1`/' | sed -E 's/    ((param|type) .*|return|rtype)/- `\1`/' | sed -E 's/    ://' | sed 's/^    //' > en/api.md
```
After generating the ReST file from the MAAS codebase.
Full instructions:
https://gist.github.com/nottrobin/df46807084219fe8d052cb42723cecad
> Add the API page for trunk

- en/index.md
- en/installconfig-images.md
Backport to devel, 2.1, and 2.0
> clarity for non-OOB images: UA required

- en/manage-cli-common.md
Fixes #248 
Adds max count flag to grep part of the cli snippet to make sure we only return 1 system ID if found.
> Fix common cli task snippet to determine system ID

- en/intro-concepts.md
The old description was a bit confusing given the addition of unmanaged subnets.
Mike Pontillo gave me a good description of what Reserved ranges do in managed vs. unmanaged subnets on maas-devel and I hope I've made good use of that here.
> Updated the description of Reserved ranges

- en/manage-cli-advanced.md
Fixes #328 
A solution without the use of 'jq' would look very ugly. It's odd to use it but I think it's better in the end.
> Assign a network interface to a fabric via CLI

- en/installconfig-add-nodes.md
Following the guide AS-IS will lead the user to unsuccessful execution of the virsh -c qmeu+ssh:// command. This is because of no mention of dependency on `libvirtd` group membership requirements for the user created on the KVM host.
> Add note about KVM host user group membership

- en/manage-ha.md
This came about after doing some testing of MAAS in HA configurations. When more then 2 region controllers are present in the HA then `max_connections` must be adjusted or MAAS will fall over.
I targeted this to master branch, but it also applies to 2.2.
> Add note to PostgreSQL HA section that the max_connections need to be adjusted based on the number of region controllers.

- en/metadata.yaml
- 1.9 docs are now properly versioned and accessible form the version number link.
> Remove top level link to 1.9 docs

- en/nodes-hw-scripts.md
fixes #576 
Fixes my own nicely constructed bug that worked with local doc builder testing and within GH's markdown preview.
> fixed image paths.

- en/metadata.yaml
- en/nodes-custom.md
fixes #588
fixes #288
fixes #283 
- migrated 1.9 rst doc to markdown
- removed defunct references to Debian installer
- removed inaccurate references to preseed (after feedback)
- updates/rewrite to hopefully make doc easier to understand
- added doc to index/contents
> 283 Migration of 1.9 preseed dev doc

- en/nodes-custom.md
#fixes #604 
- attempts to make clear this is a process MAAS calls preseed
- (temporarily) added pressed in brackets to the title to help users looking for the old 1.9 doc
> Custom node configuration aka preseed

- en/nodes-hw-scripts-fields.md
fixes #685 
- removed blank lines within nested lists
- standardised on code for metadatefields
Before: 
After:
> 685 list fix

- en/intro-concepts.md
closes #556 
closes #557 
closes #558 
closes #560 
- moved node actions before node statuses
- added to commissioning definition
- added to deployment definition
- added details on Ready state
- updated nodes description
- added more information about both rack and region controllers
> Various updates to intro-concepts

- en/contributing-git.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/724
> Backport #724 to devel

- en/contributing-git.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/724
> Backport #724 to 2.2

- en/metadata.yaml
fixes #738 
- small fix to move *Release notes* one notch down in the main main, for formatting and consistency.
> Moved release notes link in menu

- en/audit-event-logs.md
Add documentation and working examples for audit event logs in MAAS.
> Audit event logs

- en/manage-cli-advanced.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/801
> Backport #801 to 2.3

- en/manage-cli-advanced.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/801
> Backport #801 to 2.2

- .travis.yml
- en/manage-cli-advanced.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/801
> Backport #801 to 2.1

- en/api.md
fixes #834  (will fix others after this is merged).
Commands to generate this document:
```bash
git clone git://git.launchpad.net/maas
cd maas
make install dependencies
sudo apt install python-django-piston
make
make docs/api.rst
```
Command to convert *api.rst* to markdown *api.md* for documentation:
```bash
printf "Title: API | MAAS\ntable_of_contents: True\n\n" > api.md; cat api.rst | sed -n '/========/,$p' | sed 's/:/:\n / 2' | sed 's/^:\([a-z0-9 _{}]*\):/MDSTARTDEF\1MDENDDEF/g' | sed 's/_{/MDCURLYFIX/g' | pandoc --from=rst --to=markdown+backtick_code_blocks+pipe_tables+definition_lists+compact_definition_lists --column=78 --atx-headers | sed 's/MDSTARTDEF/- `/1' | sed 's/MDENDDEF/`/g' | sed 's/MDCURLYFIX/_{/g'| sed 's/:   /   /g'| sed 's/\\_/_/g'| sed 's/#### /##### /g'| sed 's/^ …
```
> API doc update

- metadata.yaml
- package.json
- requirements.txt
- Updated documentation-builder to 1.6.0, which includes Vanilla 1.7.1 styling + some slight adjustments for docs (tighter spacing, wider text max-width etc)
- Updated `metadata.yaml` with favicon, logo url, and MAAS navigation styles
- Added `--site-root` option to build script so nav logo links to maas.io
- Pull code
- Add the name of this branch to `versions`
- Run `./run`
- Go to http://0.0.0.0:8203
- Select the name of the branch from the version dropdown
- Check the styling has been applied on this branch
- Check that the other versions still work properly
> Update documentation-builder to 1.6.0

- en/nodes-deploy.md
Adds an example to deploy a machine with cloud-init user-data.
> Add example to deploy with user-data

- Dockerfile
- nginx.conf
Add net-tools to production image
So that we can use `netstat` to create a `livenessProbe` to check that a process is running on port 80.
Previously, nginx running behind a load balancer would not intelligently interpret your port or protocol, such that you could end up with the following erroneous redirect:
https://docs.maas.io:8090/ -> http://docs.maas.io/en/
These changes to the configuration make redirect work properly.
QA
--
``` bash
$ docker build --tag maas-docs --build-arg COMMIT_ID=`git rev-parse --short HEAD` .
$ docker run --name maas-docs -ti -p 8903:80 maas-docs
```
In a separate terminal:
``` bash
$ curl -I localhost:8903
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.14.0 (Ubuntu)
Date: Wed, 29 Aug 2018 13:41:14 GMT
Content-Type: text/html
Content-Length: 170
Connection: …
```
> Add net-tools, preserve protocol and port in nginx redirects

- en/index.md
- en/intro-what-is-maas.md
- en/metadata.yaml
Original design issue [here](https://github.com/ubuntudesign/vanilla-design/issues/219)
- Updated homepage with new design
- Moved original index.md to intro-what-is-maas.md
- Changed sidebar navigation to have an "Introduction" section
**Note: The demo does not show the version dropdown - this is a workaround to get the demo working with documentation-builder. The code in this PR will allow version switching**
> Update documentation homepage

- en/api.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1049
> Backport #1049 to 2.5

- en/installconfig-lxd-install.md
Found a small typo in the docs while running through a refresher of the install maas on lxd guide. 
-sfeole
> Update typo found in MAAS LXD Documentation

- en/manage-cli-kernels.md
- en/nodes-kernel-options.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1109
> Backport #1109 to 2.5

- en/manage-cli-kernels.md
- en/manage-cli-tags.md
- en/nodes-kernel-options.md
The original PR this was ported from can be viewed here:https://github.com/CanonicalLtd/maas-docs/pull/1112
> Backport #1112 to 2.5

- en/nodes-scripts-cli.md
Adds CLI example for suppressing script results using 'node-script-results update' command. This also deletes some trailing white space.
> Docs suppressed script results

- en/installconfig-images-vmware.md
- en/metadata.yaml
- Add new page for VMWare images
- Add form in modal to register and download packer script
- Go to /installconfig-images-vmware.html
- Check that page matches the [copy doc](https://docs.google.com/document/d/1798uHGFZPEsDoMob7DaDnGnM0MK_JLwTcLtSLtx-uc0/edit#)
- Click the link in the sentence "Packer template for MAAS custom image"
- See that a modal with a form appears
- Fill in the form and see that the success/thank you message appears and that the file downloads
- Close the modal and reopen
- See that the form appears and has been cleared
> Add VMWare images page and marketo form

- template.html
Added the same auto scrolling behavior to the right hand table of contents menu as the side navigation.
- Go to a smaller page like: /2.5/en/intro-requirements and see there is no scrollbar
- Go to a long page like /2.5/en/api and see the table of contents menu has a scrollbar
Fixes https://github.com/CanonicalLtd/maas-docs/issues/1165
> Add scrollbar to long TOC menus

- redirects.map
Remove 2.6, devel and redirect those places to maas.io/docs
(this will be published to old-docs.maas.io when we go live with maas.io/docs)
QA
--
``` bash
./run build
docker build --build-arg REVISION_ID=none --tag maas-docs .
docker run -ti -p 8996:80 maas-docs
```
Now check redirects work:
> Redirect devel and 2.6 to new maas.io/docs

- package.json
- yarn.lock
Fixes https://github.com/canonicalltd/maas-docs/network/alert/yarn.lock/lodash/open
QA
--
`./run build`, and then look in `node_modules/lodash/package.json` and check the version is greater than or equal to `4.17.13`.
> Fix CVE-2019-10744

- .travis.yml
- Dockerfile
- nginx.conf
- requirements.txt
- Pin gitdb: see here https://github.com/canonical-web-and-design/docs.ubuntu.com/pull/234
- Upgrade images to focal
- Use build_id instead of revision id which is our pattern
- `./run build`
- `docker build --build-arg BUILD_ID=build_id -t maas-docs .`
- `docker run -ti -p "8006:80" --env SECRET_KEY=secret_key maas-docs`
- http://localhost:8006/stable/en/
- Play around the site. Should be as usual
> Upgrade focal
